#import "../fragments/certificate.fragment.gql"

query certificateCollectionQuery {
  certificateCollection {
    total
    items {
      ...Certificate
      # add the fields you want to query
    }
  }
}
