name: gh-pages

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    environment: github-pages

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "./package-lock.json"
      - run: npm install
      - run: npm run generate
        env:
          NUXT_CONTENTFUL_SPACE: ${{ secrets.NUXT_CONTENTFUL_SPACE }}
          NUXT_CONTENTFUL_PUBLIC_ACCESS_TOKEN: ${{ secrets.NUXT_CONTENTFUL_PUBLIC_ACCESS_TOKEN }}
          NUXT_SENDGRID_API_KEY: ${{ secrets.NUXT_SENDGRID_API_KEY }}
      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ".output/public"
          CLEAN: true
        env:
          NUXT_PUBLIC_TEST_VAR: ${{ secrets.NUXT_PUBLIC_TEST_VAR }}
